In [1]:
import numpy as np
arr1 = list(range(1000000))
arr2 = list(range(1000000,2000000))

arr1_np = np.array(arr1)
arr2_np = np.array(arr2)

In [2]:
%%time
np.dot(arr1_np, arr2_np)

Wall time: 55.4 ms


-1942957984

In [3]:
# This is a list of lists...
climate_data = np.array([[73, 67, 43],
                        [91, 88, 64],
                        [87, 134, 58],
                        [102, 43, 37],
                        [69, 96, 70]])

In [4]:
climate_data

array([[ 73,  67,  43],
       [ 91,  88,  64],
       [ 87, 134,  58],
       [102,  43,  37],
       [ 69,  96,  70]])

In [5]:
# Checks the measurements of the matrix
climate_data.shape

(5, 3)

In [6]:
weights = np.array([0.3, 0.2, 0.5])

In [7]:
weights

array([0.3, 0.2, 0.5])

In [8]:
weights.dtype

dtype('float64')

In [9]:
climate_data.dtype

dtype('int32')

In [10]:
# This multiplys matrices..It does the same work as np.dot
climate_data @ weights

array([56.8, 76.9, 81.9, 57.7, 74.9])

In [11]:
yields = np.dot(climate_data, weights)

In [12]:
yields

array([56.8, 76.9, 81.9, 57.7, 74.9])

In [13]:
yields.shape

(5,)

In [14]:
# np.concatenate function helps provide the yields back to climate_data as the fourth column
climate_results = np.concatenate((climate_data, yields.reshape(5, 1)), axis = 1)

In [15]:
climate_results

array([[ 73. ,  67. ,  43. ,  56.8],
       [ 91. ,  88. ,  64. ,  76.9],
       [ 87. , 134. ,  58. ,  81.9],
       [102. ,  43. ,  37. ,  57.7],
       [ 69. ,  96. ,  70. ,  74.9]])

In [16]:
np.savetxt('climate_results.txt',
          climate_results,
          fmt = '%.2f',
          header = 'Temperature,Rainfall,humidity,yield_apples',
        comments = '')

In [17]:
arr2 = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 1, 2, 3]])

In [18]:
arr2 + 3

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12,  4,  5,  6]])

In [19]:
import numpy as np
arr1 = np.array([[1, 2, 3], [3, 4, 5]])
arr2 = np.array([[2, 2, 3], [1, 2, 5]])

In [20]:
arr1 == arr2

array([[False,  True,  True],
       [False, False,  True]])

In [21]:
arr1 != arr2

array([[ True, False, False],
       [ True,  True, False]])

In [22]:
arr1 >= arr2

array([[False,  True,  True],
       [ True,  True,  True]])

# And So Many Others

In [23]:
(arr1 == arr2).sum()

3

# That means that there are only three right bools

In [24]:
np.zeros((3, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [25]:
np.ones((2, 2, 3))

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [26]:
# Creates an indentity matrix
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [27]:
np.random.rand(2, 3)

array([[0.33858445, 0.50646671, 0.38794016],
       [0.67954167, 0.1755687 , 0.71643611]])

In [28]:
np.random.randn(2, 3)

array([[-0.08072657, -0.98200057, -0.94166002],
       [-3.53835889, -0.56504083,  0.13010278]])

In [29]:
np.full([2, 3], 42)

array([[42, 42, 42],
       [42, 42, 42]])

In [30]:
# This means that you want to start at 10 and end at ninety and still use a range of 3
np.arange(10, 90, 3)

array([10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49, 52, 55, 58,
       61, 64, 67, 70, 73, 76, 79, 82, 85, 88])

In [31]:
np.linspace(3, 30, 10)

array([ 3.,  6.,  9., 12., 15., 18., 21., 24., 27., 30.])

In [32]:
np.arange(10, 90, 3).reshape(3, 3, 3)

array([[[10, 13, 16],
        [19, 22, 25],
        [28, 31, 34]],

       [[37, 40, 43],
        [46, 49, 52],
        [55, 58, 61]],

       [[64, 67, 70],
        [73, 76, 79],
        [82, 85, 88]]])

In [33]:
#  List of functions
np.concatenate
np.min
np.max
np.mean
np.median
np.array
np.df

AttributeError: module 'numpy' has no attribute 'df'

In [2]:
import os

In [3]:
os.getcwd() # Checking what Word directory we are currently using

'C:\\Users\\Jonathan_K'

In [4]:
os.listdir('.')

['.android',
 '.config',
 '.data',
 '.idlerc',
 '.ipynb_checkpoints',
 '.ipython',
 '.jupyter',
 '.lewis.data',
 '.matplotlib',
 '.node_repl_history',
 '.vscode',
 '3D Objects',
 'AppData',
 'Application Data',
 'climate_results',
 'climate_results.txt',
 'Contacts',
 'Cookies',
 'Creative Cloud Files',
 'data',
 'Desktop',
 'Documents',
 'Downloads',
 'Favorites',
 'IntelGraphicsProfiles',
 "lewis'_new_notebook.ipynb",
 'Links',
 'Local Settings',
 'MicrosoftEdgeBackups',
 'Music',
 'My Documents',
 'NetHood',
 'NTUSER.DAT',
 'ntuser.dat.LOG1',
 'ntuser.dat.LOG2',
 'NTUSER.DAT{53b39e87-18c4-11ea-a811-000d3aa4692b}.TxR.0.regtrans-ms',
 'NTUSER.DAT{53b39e87-18c4-11ea-a811-000d3aa4692b}.TxR.1.regtrans-ms',
 'NTUSER.DAT{53b39e87-18c4-11ea-a811-000d3aa4692b}.TxR.2.regtrans-ms',
 'NTUSER.DAT{53b39e87-18c4-11ea-a811-000d3aa4692b}.TxR.blf',
 'NTUSER.DAT{53b39e88-18c4-11ea-a811-000d3aa4692b}.TM.blf',
 'NTUSER.DAT{53b39e88-18c4-11ea-a811-000d3aa4692b}.TMContainer00000000000000000001.regtrans-ms

In [154]:
os.makedirs('.lewis.data', exist_ok = True) # Creates a directory

In [159]:
'climate_results.txt' in os.listdir('.lewis.data') # Here we are confirming the presence of our file....

True

In [38]:
file = open('./.lewis.data/climate_results.txt', mode = 'r')

In [39]:
file_content = file.read()

In [40]:
print(file_content)

Temperature,Rainfall,humidity,yield_apples
73.00 67.00 43.00 56.80
91.00 88.00 64.00 76.90
87.00 134.00 58.00 81.90
102.00 43.00 37.00 57.70
69.00 96.00 70.00 74.90



In [45]:
'73.00 67.00 43.00 56.80'.split()# Split method breaks a string into a list using the given separater(, in this case).

['73.00', '67.00', '43.00', '56.80']

In [ ]:
climates = [{'Temperature': 73.00, 'Rainfall': 67.00, 'humidity': 43.00, 'yield_apples' : 56.80}]

In [190]:
file_content[43]  # Now see here you are able to access letter per letter which might make work so tiresome and of course this is so useless

'7'

In [172]:
file.close()

In [173]:
with open('./.lewis.data/climate_results.txt', 'r') as file:
    file_contents = file.read()
    print(file_contents)

Temperature,Rainfall,humidity,yield_apples
73.00 67.00 43.00 56.80
91.00 88.00 64.00 76.90
87.00 134.00 58.00 81.90
102.00 43.00 37.00 57.70
69.00 96.00 70.00 74.90



In [179]:
with open('./.lewis.data/climate_results.txt', 'r') as file:
    file_contents = file.readlines()  # This is what helps you access line per line...(readlines())

In [180]:
file_contents

['Temperature,Rainfall,humidity,yield_apples\n',
 '73.00 67.00 43.00 56.80\n',
 '91.00 88.00 64.00 76.90\n',
 '87.00 134.00 58.00 81.90\n',
 '102.00 43.00 37.00 57.70\n',
 '69.00 96.00 70.00 74.90\n']

In [197]:
file_contents[0] # Here you are accesing line per line

'Temperature,Rainfall,humidity,yield_apples\n'

In [187]:
file_contents[0].strip()  # Removes the new line tag

'Temperature,Rainfall,humidity,yield_apples'

In [7]:
with open('./.lewis.data/climate_results.txt', 'r') as file:
    file_contents = file.readlines()

In [8]:
def parse_headers(header_line):
    return header_line.strip().split(',')

In [43]:
headers = parse_headers(file_contents[1])

In [44]:
headers

['73.00 67.00 43.00 56.80']

In [46]:
def parse_values(data_line):
    values = []
    for item in data_line.strip().split():
        if item == '':
            values.apppend(0.0)
        else:
            values.append(item)
    return values

In [47]:
values1 = parse_values(file_contents[1])

In [48]:
values1

['73.00', '67.00', '43.00', '56.80']

In [26]:
import numpy
for item in zip([1, 2, 3], ['a', 'b', 'c']):
    print(item)

(1, 'a')
(2, 'b')
(3, 'c')


In [27]:
def create_item_dict(values, headers):
    result = {}
    for value, header in zip(values, headers):
        result[header] = value
    return result

In [28]:
headers

['Temperature', 'Rainfall', 'humidity', 'yield_apples']

In [49]:
create_item_dict(values1, headers)

{'73.00 67.00 43.00 56.80': '73.00'}